version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
  mysql:
    image: 'mysql:8.0'
    container_name: "another-generic-todo-db"
    environment:
      MYSQL_ROOT_PASSWORD: securePassword
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: securePassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
#  app:
#    build: .
#    container_name: app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - mysql