spring:
  application:
    name: "API-Resource-Server"
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090"
server:
  port: 7070
  servlet:
    context-path: "/api/v1"
