spring:
  application:
    name: "API-Admin-Resource-Server"
  datasource:
    url: "jdbc:mysql://localhost:3307/db"
    username: "db_user"
    password: "securePassword"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      lifecycle-management: start_and_stop
server:
  servlet:
    context-path: "/api"